# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799d3d65ead54a3fd5b1d8a182e21de0be9b3585a3338c3abf099047cf831fc462026ccdbcc8705d642f03b0c1166ce5fad2f01d1d82a7bc30f334490faea897

test:
  secret_key_base: d964786d2627e564f3c8eecb18eeb3f2fc910219f8be3a25d88146aaf40bf4f79e9b305b7fc569915ffb2d1024ed4f6ef82db5d6b5f7a23099ba391dc1061f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
